apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: k6-custom-executor
  namespace: testkube
spec:
  command: ["k6", "run"]
  executor_type: container
  features:
    - artifacts
  image: loadimpact/k6:0.41.0
  types:
  - k6-custom/script
