apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: rest-test-suite
  namespace: testkube
spec:
  description: Mirrornode REST API performance test suite
  executionRequest:
    variables:
      BASE_URL:
        name: BASE_URL
        type: basic
        value: http://{release}-rest.{namespace}.svc.cluster.local
      DEFAULT_DURATION:
        name: DEFAULT_DURATION
        type: basic
        value: "600s"
      DEFAULT_VUS:
        name: DEFAULT_VUS
        type: basic
        value: "1500"
      TEST_REPORTS_DIR:
        name: TEST_REPORTS_DIR
        type: basic
        value: /share
  steps:
    - delay:
        duration: 600000
    - execute:
        name: rest-test
