apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: mainnet
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.62.0'
  dependsOn:
    - name: mirror
      namespace: common
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: true
    timeout: 25m
  timeout: 48h
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    importer:
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "MAINNET"
        HEDERA_MIRROR_IMPORTER_PARSER_RECORD_SIDECAR_ENABLED: "true"
        HEDERA_MIRROR_IMPORTER_RECONCILIATION_ENABLED: "false"
        HEDERA_MIRROR_IMPORTER_START_DATE: "1970-01-01T00:00:00.000000000Z"
    monitor:
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "MAINNET"
        HEDERA_MIRROR_MONITOR_PUBLISH_SCENARIOS_PINGER_PROPERTIES_TOPICID: "0.0.798453"
        HEDERA_MIRROR_MONITOR_SUBSCRIBE_GRPC_HCS_TOPICID: "0.0.798453"
      prometheusRules:
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
    rest:
      config:
        hedera:
          mirror:
            rest:
              network:
                unreleasedSupplyAccounts: [0.0.2, 0.0.42, 0.0.44, 0.0.45, 0.0.46, 0.0.47, 0.0.48, 0.0.49, 0.0.50, 0.0.51, 0.0.52, 0.0.53, 0.0.54, 0.0.55, 0.0.56, 0.0.57, 0.0.58, 0.0.59, 0.0.60, 0.0.61, 0.0.62, 0.0.63, 0.0.64, 0.0.65, 0.0.66, 0.0.67, 0.0.68, 0.0.69, 0.0.70, 0.0.71, 0.0.73, 0.0.74, 0.0.75, 0.0.76, 0.0.77, 0.0.78, 0.0.79, 0.0.80, 0.0.81, 0.0.82, 0.0.83, 0.0.84, 0.0.85, 0.0.86, 0.0.87, 0.0.99, 0.0.100, 0.0.400, 0.0.401, 0.0.402, 0.0.403, 0.0.404, 0.0.405, 0.0.406, 0.0.407, 0.0.408, 0.0.409, 0.0.410, 0.0.411, 0.0.412, 0.0.413, 0.0.414, 0.0.415, 0.0.416, 0.0.417, 0.0.418, 0.0.419, 0.0.420, 0.0.421, 0.0.422, 0.0.423, 0.0.424, 0.0.425, 0.0.426, 0.0.427, 0.0.428, 0.0.429, 0.0.430, 0.0.431, 0.0.432, 0.0.433, 0.0.434, 0.0.435, 0.0.436, 0.0.437, 0.0.438, 0.0.950]
    rosetta:
      env:
        HEDERA_MIRROR_ROSETTA_NETWORK: "mainnet"
