apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBW40bi3gHQKFJsJwWk6sNQMWtmhFmd62/jBTuzMfOCPqQAIZE1plhcPZvz4ktIRfGkVUrp9Xqyd4iWdt9WONfhAcS5NKRxOzizOZ7uO4jkfO+Nr45u9QsGzQA5IPlO8r9dg5mUczlEeNiKqjQBa4ra8Qxl/+jXIsSnIvzNv0ZhWF5vS3ybm5ajA0Wp6yqlatEiB/7XlySxTAktDXOI4ZsN4dvJWVGJhcAzDaeeL8YyAQv276Aa/NovrRqVVTu1HxSxnnE9F8MpTPB9EX9RbZXs/nCdboyHxbbkyKlEMqyEhZ/9Q+qVil3ITdZC2wV9cPPpPnAexip6jMlpTjbJWlnkGblPfXn3NW70HtSBROA3xQKyG4Rf4121XIWAd0x3wnj/5rs4zCH2WiFDHhvfkdZJtBEGo+SpLGYkcVymkbOWdYnfDMiEGB18bRkpso7MYdeqTULiUfeo1qaDvwvJsgxZAbmyptv5oPyQF/gw4fkp6I4zr/ZtG8XwrJsbQ6yqFrPhrrTvu0lzr/qXpp7Cd/ngo1mDlymu9gt0DtywDhQ6vr8USDMgb8beGId6vDEXTT8hk7LLrafakEB1AOZahmsHrXcuc48h3GJM0gp2ugMPs5SvEGn514C8yQ6gILCnNeOxyiL2yV/5JmJxqCYgrYtZmpAFDKOIC7hsuFSZi2A77ckJiu92Ycym5HunKa1wb0LppyhDJxZJvD/yPaskKj2r0OOFy1RqvY/CbAzJlA3ZwHUi9m9Y9A==
    token: AgABuoR/bi+aEI8/TttmG/tV8A+GeY8O1mOsrT/cqxT+ISVj7rGm9SwkGxYtaCCwTH43AND7rAzP33FtKnMB8L2tcGxsGpZJA9VGVXSPU5Yt85v+u/RBbyGVzlc3SVsgAETHZOFnoPTVd6kTXTv+aLKT7550PMQ8rwbVkVSWkuBc592OuV6fEbw68jth3L3iXJMBBChYNL+PsrlL9LQ7zpV3illHM77h9yLLYgSy4aE5c4HJt9gbkAxvMVJEe2b0+bgjRXIuCEYiELE9WsBY8ZEnHivNd1Jx77vG9YRYsgVxhhge298fbKv+5NFZXt0M/D2bojk7GeG/AGVFWC9d2STZetJ3chdzljMgUuuRCJv8p3yThavtiDTuTEDzivqLEDaPXV53nXhzIBlhI1PTOip6iH8SK4qeItUYSkJCpoUvRiI2krLn+/Wbn0p5xCRh48MNhDJJ2Xv3CQSKUxyu/T6JpiPjpG2eVZ0ysAnUAA4+DbXLUMuZyqm/4S4XKuSxwEDSiqggmvUJYLxj0kQxqpuxPPjdGwoZUMx22gJpNH8FxZVmiM7Dnsbtm1ZEoit/w9s7we2J79VWsgElWrUGJBtX/HdxBhfBrupUgILaSMXWXr/Fqse6ZI2g9yAa65ATo36B3C/EVYevzsnq/zi9LGh0kH4wWRMPidYk/dbOzERgVT9XXezPSol5nbs79vOeczTWZ2VAMOpwGrldsmI2idffQZoj1gehHrKVR85fPrDM4ZLnWuVLA/vn79syuvqsRT4IXW3fJGs9Qxs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque

