apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgAPAouC7pHAvhcBUSkQ6HzS3ob+ndXIztyxs15w/J+zVW2S0IL9E8XN/ahJMSdGRyfh6DcjwUkeclP1kPunXv0NihEBj7QG5EdwGYKLnZS4JXNBu71g0jRwW+jLSpnmlspl1G9wFgKGa/TlCVAIOfB6X/ILe9wRFsy9Yipj8FLOkXCXZ5s7pYTyWmRSqSAFRM64sm1i4FAxEI87hF34d06FgW4BarQPOtOCC1YZoFk0USWzW6eNu9QdAr9YBtmWKXZ/nfES/8ZIkML7I8yzV+a3ZA/GIP8sIQqEzudBhGeAITE0L+SMkyqcpPnuC8x9MvYxWsgbdO5Y90IIB7Bm6qj1X4Q1oekSjD+y8fSIX88JwDKg2fSxRX2GIDcatIy5SMbiX+cIvLmOmIn8Q1MrxXev1Q/Av8n+xFky1PR5d6ddhBkGwiY7Sr/pbrfLDkPqrrCJyF/4ZxJoFRqlD/dZ2jkAKtcWS7F50P4RJMnErWb/4XsZtzug7UYejh1uC9VmbVLyqEU94dKWrsMHkhJai6xOKWCteG41K/Hf5tJSCRXqKwTAzrkdqPFK7Y6IGJ1WHLVSqNgg7d7Y6N7B2+70f7Kbnu+lxIFuttIHA9v6MDwQDjwT1yy+FUb+5xcDNOdpmIppym0ReDWElkazjNSzh1kKAo/XVGV1Ewd3tWcTZcCDcJtiEZBOyI5Velmznr42GNiJFZb83o/1Tz1uyyDvqbtjZK1WVmO3jsaSg88naXkMLv+3OoQifQ==
    token: AgBd6vpjQqIv3fiubTcEXzWakijM33Bb/PWrgSvA3IeqqwUnYLYCB+7KyVaAbbUKCUWEUjtDasWOB/I80/XkSiKW1Ij3ezSBVBfww5qKNtGq3lh/vbySh47jDvOE8dKCeFW5uqKH+6ereJWFQ1+kXo+Kz5ndk8YHpXG2jpSaPUTajNWLPc4BsLXDNaDjfBQRMd1XeQk/4JMxRFngZc8vxWJBHffDUsBfwzXotRevoARGw2eqcKeorYMI4SNY1QCDKJx1b+dDUqxqg8mjD3xZsA8oqKDM08cTISMDR40n5D6KKHaZDKAns4mGbsGiuRN6IoiPvrJKhorFmBI98QRjXDEQikQqiBQ2arw5iBPVdeoXpUtAlUtF8utPlcNvjfxKVr3tWv/57/hs5Tq2hywmQzfU62QDuyFtiY9Uz++iNhNkkRgixQg3sw+L/dY2eC1UoWXClyZpOzpTsQhOIdelQMnl/fNQWhF41ToM9opjkd3RFuAexbStVOnG/fSfqMJmlQvCL+JgK4MCHRVFF7/qyidNKTfVuH+Lv9zlbxJaUMNsMa9HWcgQnOCUGAWwLRKs76kqkEZqBF1m8UNAWs53b+JW/EAkxMKd9lXcgOUrFFN7LsjFS2cGRfmfmOZLL9w/fXgJP6JYcWMC34xdr8dD0cgaArJBQUSYE2oOq5DbSOvq4nh1J5Ghif+5QBBgl0ihi9/omJDdPi9oONJPBH4hdOGnqS25/i4grfK8m2H8urfpyIlvoY5xhzpT/wmmZJMjjk0bZ4uG4SCXfIw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque

