apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgAhzFFgU+ctGMCM+VAipu/FEmpRN1GOTSzN0ge3mDfHJcwLEdgGxE0pKuUAtrabVMAR6PjqGMznZpuW0dhyx0y/V1XBF6vnyi3PNsQDr9Y9YvCPafnZr3Q4MFi14CdMRAk7wt1ZSJtIWIaDsuJ5RC9l+hhp5gpwGIKUZlbUrfPCg5sSk7u+5jpblcx4iiQZ3TIECvAODR0z7Ivz3FUxTQ/xU8+GMKNKTnba7xr1HodvUS1zdv4/nWbtT2bf+i2zpsUCUTC8NqrpCLNm+2FRbod1Rvza0JKDK72wXWAoG9V7pFge9wVmWHF+yXstFKhtXHN5Fftop/7gf3GR+6aGrpXuTThF2fbouwFQm/n47tG8uoDQh/UrrZYX5kGR6zZuC8/wmiZZWQwx/dUZS+++FtKxyj5xIMWbEndSBi/xN1fFDv9HST9QgPkdNOMvdb1YFBb7yAGA4gtz4wxxo67Ql0Y8natFSXXb4orx2hbv4o3JqzCU8a9Oj20CuVcZ6zQAHd/Hxg82KCB+mqMZELh7sih0K2axxxAGi08A8elunJo21A32HQUvx+n1aQZtxG1IJo5dRl1t3PvzsALfmTuettD1Qtm9RG7gcJitpMEG7z4uXpSkhiQqICBs0xJPuHHLCLJO8LpETAlrWd34/Ud8SYRueIkBNZs/2kpDQOp0fVThf2DRD/WxVFbBNApKhP2t45bwhQn0S6z6X+Rg26aWZl4mskehKb+ZX92oaVtRUPzhaH1m5DQpbA==
    token: AgAz+YPuR35KVUbEdOaRjH4F0x166IwWLig//gT/wAHZZ/Wv2tMyaY2fu4F+/1ji13vr7/vmtwElQ1ou0uvrcmJ+TKEGMJlXrPyz5j55XccPJ2ZSrQyEU8pwVRPCPVtjNgfk5sBHWxVjbJKJlYqHuD6RTWuiRHKuidWdq7+hnit5ADnOo7FcQn7A5qFJMjCu5+b3FT9iZ65wrV1Wky6u1JIMGcSxh2SHNcV2QZ9hzBP1eBdXnO9KZ8zCfEOM0o5fXvnFy4CQg8kRpv7clzpJm+poFrsPpPkPnV+nDohYpbymTzsnegAOQK/HZVd1YOXANmbobaGNvbTso/fC5Ln+gHKKlnNr2MqR5br3hsXrvQGCVu3mIQ38toE2227sszx50RWnt4gbz5vKdR2bediOBGEZIa44oN2dl+8R4b44hsmlkevs4aXTKjmZ0MMeYMSzCahw9FtsX7GjRAWMw0v+oHYIURtGqZ5lOOwc2GOT8L9U2EqW5ZuR5wp1nq73QE30vWYM4Y62/+OVgRHtvKIBVjqdw1KBwuqTIEu7Ih14V6hAgXpI1TYuPVZUnkx0/HLme3LMQPMgkmkkJ2BblbOXk0PYWCN7YSTbiJav1TO0WfGCxmWE38DllMAm/XSLPwNSE5w7V5D8sW8I3bIK8EoQx4VQn7DSQKIfJ9KDx1u23INDoSqEx8VrmoyeFcmJZtbbHuTiVou8kJ8ijV8sE1eb12apFBekUgHmSx5t5YimUKWs15kh/31E1IbwL2P5Cq9Puj/AVZVE8nhB/MY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque

