apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: performance
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.45.0-rc2'
  dependsOn:
    - name: mirror
      namespace: common
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: false
    timeout: 16m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 20
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    importer:
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "OTHER"
    monitor:
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "OTHER"
      prometheusRules:
        MonitorPublishErrors:
          enabled: false
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    postgresql:
      enabled: false

