apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mirror
  namespace: mainnet
spec:
  chart:
    spec:
      chart: hedera-mirror
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-prod.yaml
      version: '0.44.2'
  dependsOn:
    - name: mirror
      namespace: common
  install:
    crds: CreateReplace
  interval: 90s
  test:
    enable: false
    timeout: 5m
  timeout: 48h
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 20
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    importer:
      env:
        HEDERA_MIRROR_IMPORTER_NETWORK: "MAINNET"
        HEDERA_MIRROR_IMPORTER_START_DATE: "1970-01-01T00:00:00.000000000Z"
    monitor:
      env:
        HEDERA_MIRROR_MONITOR_NETWORK: "MAINNET"
        HEDERA_MIRROR_MONITOR_PUBLISH_SCENARIOS_PINGER_PROPERTIES_TOPICID: "0.0.797576"
        HEDERA_MIRROR_MONITOR_SUBSCRIBE_GRPC_HCS_TOPICID: "0.0.797576"
      prometheusRules:
        MonitorPublishLatency:
          enabled: false
        MonitorSubscribeLatency:
          enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
    rest:
      ingress:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: ""
        middleware:
          enabled: false
    rosetta:
      env:
        HEDERA_MIRROR_ROSETTA_NETWORK: "mainnet"
