apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBjA8yw9qQQntMP2c7Bsei2OsWvDWZxKs96ws7c3tKNay4sWQ/EOGlr2GrfRe3tZ6+sgkP0m+XrWynVXg4jQ6z6qaK0Xbby3DMhCuYttz4GnOexz6X4QR7wSTQkpD2a6y6ORS7WYCggmkelRRzqHGNcnltdhXQhpI81i7nECNWEOmrtzezQaZNDnrQcs53C4zXWfuKrdLkpzPWP2KCkecCIXQ8du04xC2ajLhK5rkKtLJj4GdQbNdIYWY4YruxCnqKKrZoUYVGWY7o99Oc7e2pOvdsWehP+w0I1fEt4hD3hp9dvuYpv3FTkQCG/4+zlaAycL6qK4PScYPe17U/Lbj6uYe/rJkpCJakEVYiKfRkrMiVcfoZxIRgJBym3S/P2L9SugOZ83JmRGpwFtQFqzbVdO0dFRbeiF4dHq2iwiNJcgTZX14AF3Z+ZJLo+5HnYFcuAUUNlBT2qDPcRWuFsin82A/kAKRtd4INSyInBbnX789Czcs1+ipZdPrVtw9CDGjxi5+L3mmR4j8Rdnf5HdVnJ8Xu6ajiCJZHZPfvSG9pQfc3Ht8DHyi7Sgm91WarxRdmKG6BSUKpp46THMa4JT/HasyJwdQPnmSoTi2+AN/hQw1/wwiGGYK8qvQ+68+aIQD0QTTRJoHaRxnP4CazWAAzQN3OL7fMAfrjXJTH/3LZi30bMdGthwzQGzc9Dqfu8+Dq+Bxq8Sa/nqGhBnqlhu1O2zU8J3q2Ub5jfVZyqFlf4HPGjEK0QPw==
    token: AgAsxUEdZQXmt+tIMHY7HqD3ux3a9QfucXeHBWQyoI80XuNo279vx0AzGoej0SpQ7Ubfi7a/zw02THGJ06/FI6Z261Rt6DWagcB9JmSVVa5G5XsGn/2q6yu84L8xm4MePPcqdFVXe7JLi+KpWUnQYUNy8ZIp+WXI0bU1gcQhCbDNA5LMEFshMMLuP4TKMvjfNVioz5w8yoQli6sJadJt2rZe8eeCqIaeDH+VGmLqLq9QZuuwcMPhRNCoa0A4wLhwgDXTsvGSl7ChXrJh2UNhiYhMVDrQ54fgXbhgyUvD++1ruKvo43MtNTZRwjCW7v+7sATzeC4qg0GgXKl0+mpCjlppbTnLgetIChiLvapxFi2i9i6gh7btOsTO/rXLiB7L7UJG9mTaPtilYbXK9MHkXZUWrWlCCdAUXkydAG0zUjgqA/5vurmZt9Hbe/YdjRMvSsAOl+mn4sT0CRoj1JcIjyrYrvdSSnORJex+qaeAEFEW2fATXKNGY2i40tiOoyo+ZkfdkCJN20P9xkPwbZJ8E/9WJ53rxnFOMMmSv6AUAqqzYxCJbFOdTsxGfvF4VDvPeSfUyKvmMKGkaKTSzLVpnviy6caF9ifygokq+jjMC8iZMsUZWUwkrAxxdqVeLzGG+m0EAYxS33IyXC8pk9xHCFc4AbSP/krJO0gR8KnDCS/3YYazy4fOLvGwl4jhQ1WSjWrLbVsrZI6IVM1n0idF3pkeOBdqk9j0f2jwau02t8x480bRsNJgdWbxKMke7sEkswQjJcXpocnBq/A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque

