apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBpyPfED5dDXvvOneB5Ny5RCE5bEwg0YrQ5A8TnpsszrJaNWzcAuNlXMzZ6qqrtJiiLCxmuAzhCK/ba5DqvwO4Xtl90TrBkSut/WYunQ76N6Gh+DPO4oM4/PEeqeR2vZNHNsclVK8P2/LuMzQhPnBml91ettBhbypAHDuTX608Ssj1JlzBisuR9v0J5xswnxNaBmOFdgysG794iZcltKKZuMcjnF2mkig0gNkgkvUWtChcRPgTq+eEDbOGwTqu8xOy9UqWDWA5vxSu3JLUXw9Acf2AgW2E+XD57aI1GOY88Wh0GMhYsyYGA3FIeodlqrEhTK9JKFCAOQxEjlqKz8myQPH3gwflEUba/d01GAHRBYwaZ+jkP0wcOmyPUv7TugLrZJWUitFV4hQMCLInT37h6q8xLwhD5gaCdq4yLlW9lsojT9Z1BWGF6VU1qzLe405cGuYrT4r6TTFDezCopZYAnmFMur6KRlqgKKa8p2wMce1KKwnb/y3zAwlQ6cHG7PF9FwUk//fzzARCfkSwuDmNA969Zz+I5rPhIYLYsgyx+xVwrjEJI6t8nsW3yqeGn2LA5xXCvbV6UL9IhmTjWP73Ix0yA/1AylDUL7maCoLni6KfEgL2g4/RgSVxxfSV2nvAIyWq3Ao3qxD4hUKk+AkpkMaL2lh43+wGTMBJIOHa9fM0+5taNQTVU6sb8Z697B03zbvdNg7hxnFJHi6NTeJoREmkRVOnE1cdsB4Sx4eOLVVJOCf+4+Q==
    token: AgA7pKIuVvETmwYL/GMhEktsp1zeikuELoamhFZg7anegtxw0jjTb6hM4tmRNwKfQ9xn7u98GD7ttkepM2l3a/DGh7iVy9K/pdXyIThb5XZ71eMGFDU3eQVDYQDZR24LtcnlvfKnsklo7YkHiQVzjTQZAt0KzbmOjUW8EAuaeBYdiK33Hbpd5xBeYLMDoskbhu+SdFLi6OPlS4Bt1LAGDu2woJNwfjw6XrNDOiryiREEDYeZsSAAp1hSjly+/VAKJz4vEuBMzdDF8m7Iy+9PLM6+XFsHMT7akRoWZsOlzHXHjGB/BbYS1AIIFPs4ft90KEGcnNT8ys6ZNC/mYACloENRvg2f4+iQGLpvqCtAZKUFLTmJybpmSFXndyD7WDXUlAtpBDpc75ztoTPXCyhUmwr2tCrgokzRvuUoSuzm3H9hLX3x9UqAUZH/mbD9+aXEXUdGerbnmFO8hPApnSae29iOSgfmlPOlycIDl5s1Joj6U5WS1NfRNTd2E6Yr38WjJclTK3dL1qvztNnPtZcthW90UogoEi2SuQfy+b5sgduApHXaLZrtOuFGzPChqFE5tNdJ0P4H3mXiXvg/cAQU1FO+dSk9ihgmf/21ov6PJw5I3d4HFvQxG1Pj9Q/8QgV/R3V/OGtD6BgBoyF4UCYEPRuB0ZVa/Tp5ijRcu1RfiUhacQ82BbBvXr7O9nBLIwy9u9IojNST3wSjUqF8xPxUI8+5Dx9DFtWI7TTE5jm0EiNutM+9vmnT2MtN/cwZvxGfg+3+HTArCs+pH/8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque

