name: "GCP Marketplace"

on:
  push:
    branches: [ 04801-Updating-gcp-marketplace-version ]

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      MPDEV: "/home/runner/bin/mpdev"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install k3d
        run: curl --retry 3 -fsL https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Create k3d cluster
        run: k3d cluster create mirror --agents 1 --timeout 5m --wait --image rancher/k3s:v1.24.3-k3s1
        timeout-minutes: 3

      - name: Install kubectl
        run:  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/amd64/kubectl"

      - name: Get tag
        run: echo "TAG=0.68.1" >> $GITHUB_ENV

      - name: Create bin
        run:  cd ${HOME} && mkdir "bin" && export PATH=${HOME}/bin:$PATH && echo "Path is ${PATH}"

      - name: Install mpdev
        run:  docker run gcr.io/cloud-marketplace-tools/k8s/dev cat /scripts/dev > ${MPDEV}
               && chmod +x ${MPDEV}

      - name: Install application
        run: kubectl apply -f "https://raw.githubusercontent.com/GoogleCloudPlatform/marketplace-k8s-app-tools/master/crd/app-crd.yaml"

      - name: Install marketplace app
        run: ${MPDEV} verify --deployer=gcr.io/mirror-node-public/hedera-mirror-node/deployer:${TAG} --parameters='{"rest.service.type":"ClusterIp", "grpc.service.type":"ClusterIp"}'
